### ISSUE TITLE
Pros/Cons in team work vs solo work

### ISSUE THREAD

**Issue by Warpeas** [cs304-spring2021/class-discussion-sakuraknight#1]

**Comment by Warpeas** [comment]
Team: Much need documentation

**Comment by SII-WANGWei** [comment]
Team work may cost more time compare to SOLO.

**Comment by si-e** [comment]
SOLO is easy to go to a dead end

**Comment by si-e** [comment]
Flying alone may lead to poor time management, resulting in the task can not be completed well.

**Comment by si-e** [comment]
SOLO may lead to poor time management, resulting in the task can not be completed well

**Comment by Warpeas** [comment]
End of class discussion
